### ISSUE TITLE
Multiple partial charges calculations

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/offpele#14]
It is possible to use Antechamber with different calculation methods to extract partial charges from a structure. We should investigate if there are other methods that can be used to generate partial charges faster than the current method (`am1bcc`).

**Comment by j-wags** [comment]
`gasteiger` is a faster charge method, however it is much lower quality than `am1bcc`

**Comment by martimunicoy** [comment]
Thank you! I will give it a try. Having something faster than `am1bcc` can be useful for tests, as you suggest.
