### ISSUE TITLE
Assign Molecule's connectivity with an RDKit template

### ISSUE THREAD

**Issue by martimunicoy** [martimunicoy/offpele#51]
# Description
If we want to load PDB files with no connectivity data (such as those coming from PELE simulations) we need a method to assign the missing connectivity.

# Solution
We can use an `RDKit` molecule representation with the correct connectivity assigned as the connectivity template. Then, the `RDKit`'s method `AllChem.AssignBondOrdersFromTemplate` can be employed to assign the connectivity to a third molecular representation using the previous connectivity template.

**Comment by j-wags** [comment]
I just recently saw that MDAnalysis has added a to_rdkit method, and that they put some solid work into guessing valid connectivities + bond orders. It may be worth checking this out: 

MDAnalysis PR: https://github.com/MDAnalysis/mdanalysis/pull/2916
Blog post from author about guessing connectivity: https://cedric.bouysset.net/blog/2020/07/22/rdkit-converter-part2
